reason: fixes

diff --git a/main b/main
--- a/main
+++ b/main
@@ -13,20 +13,20 @@ if [ ! -f track/track.tck ]; then
 	time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./segment_tracks.sh
 fi
 
-if [ ! -f ./wmc/classification.mat ]; then
-	time singularity exec -e docker://brainlife/dipy:1.4.0 ./classificationGenerator.py
-fi
+#if [ ! -f ./wmc/classification.mat ]; then
+#	time singularity exec -e docker://brainlife/dipy:1.4.0 ./classificationGenerator.py
+#fi
+#
+#if [ ! -f ./wmc/surfaces/index.json ]; then
+#	time singularity exec -e docker://brainlife/pythonvtk:1.1 ./rois2vtks.py
+#fi
 
-if [ ! -f ./wmc/surfaces/index.json ]; then
-	time singularity exec -e docker://brainlife/pythonvtk:1.1 ./rois2vtks.py
-fi
-
-if [ -f ./wmc/classification.mat ]; then
-    mv *track*.txt track*.tck ./raw/
-    echo "complete"
-    exit 0
-else
-    echo "tracking failed"
-    exit 1
-fi
-
+#if [ -f ./wmc/classification.mat ]; then
+#    mv *track*.txt track*.tck ./raw/
+#    echo "complete"
+#    exit 0
+#else
+#    echo "tracking failed"
+#    exit 1
+#fi
+#
